# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('group_type', models.IntegerField(blank=True, null=True)),
                ('group_section', models.CharField(max_length=40)),
                ('student_counter', models.IntegerField(blank=True, null=True)),
                ('has_changes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('self', models.BooleanField(default=False)),
                ('ap1', models.BooleanField(default=False)),
                ('ap2', models.BooleanField(default=False)),
            ],
        ),
    ]
