# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papinotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papinotas.Groups'),
        ),
    ]
